# This is a templated file which is used by the krew-release-bot
# from the GitHub Action to raise a pull request to the krew-index
# (https://github.com/kubernetes-sigs/krew-index) with the correct tag
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oomd
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jdockerty/kubectl-oomd/releases/download/{{ .TagName }}/oomd_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./oomd"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomd"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/jdockerty/kubectl-oomd/releases/download/{{ .TagName }}/oomd_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./oomd"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomd"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/jdockerty/kubectl-oomd/releases/download/{{ .TagName }}/oomd_{{ .TagName }}_windows_amd64.zip" .TagName }}
    files:
    - from: "/oomd.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomd.exe"
  shortDescription: Show recently OOMKilled pods
  homepage: https://github.com/jdockerty/kubectl-oomd
  description: |
    Display pods and their corresponding containers which have recently
    been 'OOMKilled'
