apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oomd
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha ""https://github.com/jdockerty/kubectl-oomd/releases/download/v0.0.2/oomd_linux_amd64.tar.gz"" .TagName }}
    files:
    - from: "./oomd"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomd"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha ""https://github.com/jdockerty/kubectl-oomd/releases/download/v0.0.2/oomd_darwin_amd64.tar.gz"" .TagName }}
    files:
    - from: "./oomd"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomd"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha ""https://github.com/jdockerty/kubectl-oomd/releases/download/v0.0.2/oomd_windows_amd64.zip"" .TagName }}
    files:
    - from: "/oomd.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomd.exe"
  shortDescription: Show recently OOMKilled pods
  homepage: https://github.com/jdockerty/kubectl-oomd
  description: |
    Display pods and their corresponding containers which have recently
    been 'OOMKilled'
