apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oomlie
spec:
  version: {{ .TagName }} 
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{ addURIAndSha "https://github.com/jdockerty/kubectl-oomlie/releases/download/{{ .TagName }}/kubectl-oomlie_linux_arm64.zip" .TagName }}
    files:
    - from: "./oomlie"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomlie"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{ addURIAndSha "https://github.com/jdockerty/kubectl-oomlie/releases/download/{{ .TagName }}/kubectl-oomlie_darwin_amd64.zip" .TagName }}
    files:
    - from: "./oomlie"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomlie"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{ addURIAndSha "https://github.com/jdockerty/kubectl-oomlie/releases/download/{{ .TagName }}/kubectl-oomlie_windows_amd64.zip" .TagName }}
    files:
    - from: "/oomlie.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oomlie.exe"
  shortDescription: Display pods which have recently been OOMKilled
  homepage: https://github.com/jdockerty/kubectl-oomlie
  description: |
    Display pods and their corresponding containers which have recently
    been 'OOMKilled'
